/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Product = IDL.Record({
  'descriptionHindi' : IDL.Text,
  'descriptionEnglish' : IDL.Text,
  'nameHindi' : IDL.Text,
  'nameEnglish' : IDL.Text,
  'price' : IDL.Nat,
  'priceLabel' : IDL.Text,
});
export const ShopInfo = IDL.Record({
  'ownerName' : IDL.Text,
  'phoneNumber1' : IDL.Text,
  'phoneNumber2' : IDL.Text,
  'address' : IDL.Text,
  'shopName' : IDL.Text,
  'gstinNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  'addProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProduct' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
  'getShopInfo' : IDL.Func([], [ShopInfo], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Product = IDL.Record({
    'descriptionHindi' : IDL.Text,
    'descriptionEnglish' : IDL.Text,
    'nameHindi' : IDL.Text,
    'nameEnglish' : IDL.Text,
    'price' : IDL.Nat,
    'priceLabel' : IDL.Text,
  });
  const ShopInfo = IDL.Record({
    'ownerName' : IDL.Text,
    'phoneNumber1' : IDL.Text,
    'phoneNumber2' : IDL.Text,
    'address' : IDL.Text,
    'shopName' : IDL.Text,
    'gstinNumber' : IDL.Text,
  });
  
  return IDL.Service({
    'addProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProduct' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
    'getShopInfo' : IDL.Func([], [ShopInfo], []),
  });
};

export const init = ({ IDL }) => { return []; };